### ISSUE TITLE
make failure modes better when struct names are wrong

### ISSUE THREAD

**Issue by justinnoah** [docopt/docopt.rs#99] opened 2015-02-20 07:13 UTC
The following is supposed to allow IPv4 and/or IPv6 while restricting ip/port to -4 and ip6/port6 to -6. I would like it to catch the case where -4 and -6 are both missing, but I can do that elsewhere in the code. Here is an example of syntax that works on try.docopt.org, but fails with docopt.rs:

```rust
extern crate docopt;
extern crate "rustc-serialize" as rustc_serialize;

use docopt::Docopt;

static USAGE: &'static str = "
Usage: rtracker [(-4 [--port=<port> --ip=<ip>])] [(-6 [--port6=<port6> --ip6=<ip6>])]
       rtracker (--help)

Options:
    -h,  --help      Show this message
    -4               Enable listening on an IPv4 address
    --ip=<ip>        IP (v4) address to listen on [default: 127.0.0.1]
    --port=<port>    Port number to listen on [default: 6969]
    -6               Enable listening on an IPv6 address
    --ip6=<ip6>      IP (v6) address to listen on [default: ::1]
    --port6=<port6>  Port number to listen on [default: 6969]
";

#[derive(RustcDecodable, Debug)]
struct Args {
    flag_4:     bool,
    arg_ip:     String,
    arg_port:   u16,
    flag_6:     bool,
    arg_ip6:    String,
    arg_port6:  u16,
}

fn main() {
    // parse commandline args
    let args: Args = Docopt::new(USAGE)
                            .and_then(|d| d.decode())
                            .unwrap_or_else(|e| e.exit());
    println!("arg: {:?}", args);
}
```

[try.docopt.org](http://try.docopt.org/?doc=Usage%3A+rtracker+%5B%28-4+%5B--port%3D%3Cport%3E+--ip%3D%3Cip%3E%5D%29+%28-6+%5B--port6%3D%3Cport6%3E+--ip6%3D%3Cip6%3E%5D%29%5D%0D%0A+++++++rtracker+%28--help%29%0D%0A%0D%0AOptions%3A%0D%0A++++-h%2C++--help++++++Show+this+message%0D%0A++++-4+++++++++++++++Enable+listening+on+an+IPv4+address%0D%0A++++--ip%3D%3Cip%3E++++++++IP+%28v4%29+address+to+listen+on+%5Bdefault%3A+127.0.0.1%5D%0D%0A++++--port%3D%3Cport%3E++++Port+number+to+listen+on+%5Bdefault%3A+6969%5D%0D%0A++++-6+++++++++++++++Enable+listening+on+an+IPv6+address%0D%0A++++--ip6%3D%3Cip6%3E++++++IP+%28v6%29+address+to+listen+on+%5Bdefault%3A+%3A%3A1%5D%0D%0A++++--port6%3D%3Cport6%3E++Port+number+to+listen+on+%5Bdefault%3A+6969%5D&argv=--ip+0+--port6+5+-6) shows that the reference implementation is ok with this syntax. docopt (0.6.38) chokes with correct parameters by resulting in:

    Could not find argument '<ip>' (from struct field 'arg_ip').

And when the arguments are incorrect (this behaves as expected):

    ./rtracker -6 --port 55
    Invalid arguments.

    Usage: rtracker [(-4 [--port=<port> --ip=<ip>]) (-6 [--port6=<port6> --ip6=<ip6>])]
           rtracker (--help)

**Comment by BurntSushi** [comment] 2015-02-20 12:06
This is actually working as expected. The problem here is that the failure mode is terrible and that should be fixed (I've changed the title of your issue to reflect that).

The problem is how Docopt things are mapped to struct fields. It's documented, but it's buried in the `README`:

```
-g            => flag_g
--group       => flag_group
--group <arg> => flag_group
FILE          => arg_FILE
<file>        => arg_file
build         => cmd_build
```

So in your case, you'd want `flag_port` instead of `arg_port`. Indeed, swapping these makes your example work just fine (after swapping the rest too). The `arg_` prefix is reserved for *positional* arguments.

Finally, if you change your usage string to use alternations, then you can get your originally desired behavior of catching the case where neither `-4` or `-6` are specified:

```
Usage: rtracker ((-4 [--port=<port> --ip=<ip>]) | (-6 [--port6=<port6> --ip6=<ip6>]))
       rtracker (--help)
```

Although, it would be understandable to continue with what you're doing and handle this case explicitly, because the error message for running your command without a `-4` or a `-6` is simply "Invalid arguments. Here's the usage again:" which isn't terribly helpful. (Basically, Docopt is saying that it can't find a match, but it doesn't know how to say *why* it can't find a match.)

**Comment by brutal-chaos** [comment] 2015-02-20 19:20
@BurntSushi I read the readme many times, I can't believe I missed that. Thank you for pointing out that I needed flag_ rather than arg_. Your suggested usage string, however, does not allow for both -4 and -6 to be used simultaneously. 0.6.38 [isn't building](https://github.com/docopt/docopt.rs/issues/100) currently, so I have not tested the struct parameter prefix changes, but I believe that will be the change I need.

**Closed** 2015-07-27 23:09 UTC
