### ISSUE TITLE
rustc-serialize deprecated

### ISSUE THREAD

**Issue by sevagh** [docopt/docopt.rs#214] opened 2017-05-29 19:10 UTC
Hello,

Are there any plans to replace `rustc-serialize` with serde in this crate?

**Comment by BurntSushi** [comment] 2017-05-29 19:16
This is a duplicate of #128.

I added a status update: https://github.com/docopt/docopt.rs/issues/128#issuecomment-304717764

**Closed by BurntSushi** 2017-05-29 19:16 UTC
